version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AUTOSCORE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - autoscore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  api_risk:
    build: ./Apis/risk_score
    environment:
      URL_API_ZIDRA: ${URL_API_ZIDRA}
      USUARIO_ZIDRA: ${USUARIO_ZIDRA}
      PASSWORD_ZIDRA: ${PASSWORD_ZIDRA}

      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_AUTOSCORE}

    ports:
      - "8000:8000"
    networks:
      - autoscore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  n8n:
    image: n8nio/n8n:latest
    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB_N8N}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

      GENERIC_TIMEZONE: America/New_York
      N8N_HOST: "0.0.0.0"
      N8N_PORT: 5678
      N8N_PROTOCOL: http

    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - autoscore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  autoscore_net:
    driver: overlay

volumes:
  postgres_data:
  n8n_data:
