FROM n8nio/n8n:latest

# Crear usuario personalizado
RUN addgroup -g 1001 -S nodejs && \
    adduser -S n8n-user -u 1001

# Configurar permisos
USER n8n-user

# Variables de entorno predefinidas
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=contrasena_segura
ENV GENERIC_TIMEZONE=America/Bogota

# Puerto
EXPOSE 5678